// COS202 - Object Oriented Programming Explanations Database

const COS202_EXPLANATIONS = {
    "cos202_001": "POP focuses on functions and a sequence of tasks (top-down), whereas OOP focuses on data encapsulated within objects (bottom-up).",
    "cos202_002": "OOP follows a bottom-up approach where programs are organized around objects, contrasting with the top-down approach of POP.",
    "cos202_003": "Java is case-sensitive; the file name must exactly match the class name and end with the .java extension.",
    "cos202_004": "The void keyword specifies that a method performs a task but returns no information to the caller.",
    "cos202_005": "Java variables are classified into three types: local variables, instance variables, and class (static) variables.",
    "cos202_006": "Instance variables have default values; for numerical types like int, the default value is 0.",
    "cos202_007": "The instanceof operator checks whether an object is an instance of a specific class or interface type.",
    "cos202_008": "Encapsulation (data hiding) involves making fields private and providing access to them through public getter and setter methods.",
    "cos202_009": "Abstract classes are designed to provide a common design for subclasses to inherit from; they are incomplete and cannot be used to create objects directly.",
    "cos202_010": "Unlike classes, interfaces in Java allow for multiple inheritance by enabling a class to implement multiple interfaces.",
    "cos202_011": "Java does not support multiple inheritance with classes to avoid complexity, but interfaces allow a class to inherit behavior from multiple sources, defining a set of methods that must be implemented.",
    "cos202_012": "static is a non-access modifier that relates to the class level rather than the instance level; the primary access modifiers are public, private, protected, and default.",
    "cos202_013": "The finally block is guaranteed to execute after the try and catch blocks, making it ideal for resource cleanup (like closing files or database connections).",
    "cos202_014": "The term comes from the Greek 'poly' (many) and 'morph' (form); it allows objects to be treated as instances of their parent class or implemented interfaces.",
    "cos202_015": "The Runnable interface requires the implementation of the run() method, which contains the code to be executed by the thread.",
    "cos202_016": "A Stack operates on the LIFO principle, where the last element added is the first one to be removed.",
    "cos202_017": "A constructor is called automatically when an object is created; it has the same name as the class and no return type.",
    "cos202_018": "The correct syntax for array declaration in Java is type[] variableName = new type[size];",
    "cos202_019": "Every class in Java, whether explicitly declared or not, implicitly inherits from the java.lang.Object class.",
    "cos202_020": "An abstract method is declared without an implementation (no curly braces); the subclass is responsible for providing the implementation.",
    "cos202_021": "The remainder operator (%) returns the value left over after integer division; for example, 10 % 3 returns 1.",
    "cos202_022": "An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key, all of the same type.",
    "cos202_023": "The superclass (or parent class) provides a common base for subclasses, promoting code reusability through inheritance.",
    "cos202_024": "Quadrilateral is the most general class that encompasses all four-sided polygons, making it the appropriate root for the hierarchy.",
    "cos202_025": "Java Applets were historically designed to be embedded in HTML pages to run in a Java-enabled web browser, providing interactive features.",
    "cos202_026": "Abstraction allows the programmer to focus on what an object does rather than how it does it, simplifying the interface for the user.",
    "cos202_027": "The try-catch mechanism allows the program to attempt an action and provide a specific path (the catch block) to handle errors if they occur.",
    "cos202_028": "The super keyword is used to refer to the immediate parent class object, allowing the subclass to invoke parent methods or constructors.",
    "cos202_029": "A static variable belongs to the class itself, meaning there is only one copy of it in memory regardless of how many objects are instantiated.",
    "cos202_030": "Debugging is an essential phase of development where developers trace the program to find and fix bugs (errors or unintended behavior).",
    "cos202_031": "Packages are used to group related classes and interfaces, helping to manage code complexity and avoid name conflicts between classes.",
    "cos202_032": "An Iterator is an interface that provides a uniform way to access elements in a collection, regardless of the collection's underlying implementation.",
    "cos202_033": "A Queue follows the FIFO principle, where the first element added is the first one to be removed, similar to a line of people waiting for service.",
    "cos202_034": "The base case is the terminating condition in a recursive function; without it, the function would call itself forever, leading to a StackOverflowError.",
    "cos202_035": "In event-driven programming, the execution flow is controlled by events generated by the user or the system (such as clicking a button), rather than a strictly linear path.",
    "cos202_036": "List is an interface, so it cannot be instantiated directly. You must use an implementation class like ArrayList or LinkedList.",
    "cos202_037": "An event listener is an interface (e.g., ActionListener) that provides the contract for handling specific events, such as clicking a button or typing in a text field.",
    "cos202_038": "print leaves the cursor on the same line, while println (print line) moves the cursor to the beginning of the next line after outputting the data.",
    "cos202_039": "Inheritance allows for code reuse and hierarchical organization by enabling a subclass to extend a superclass.",
    "cos202_040": "Static methods belong to the class itself, so they can be invoked using the class name rather than needing an object reference.",
    "cos202_041": "The try-catch block is the standard mechanism in Java to intercept and manage runtime exceptions like division by zero.",
    "cos202_042": "A Stack (Last-In-First-Out) behaves like a stack of plates; a Queue (First-In-First-Out) behaves like a line of customers at a service counter.",
    "cos202_043": "If a method is declared final, it cannot be modified or overridden by any subclass, ensuring the implementation remains consistent.",
    "cos202_044": "Threads allow for multitasking within a single application, enabling different parts of the code to execute concurrently.",
    "cos202_045": "this is a reference variable that refers to the specific object upon which a method or constructor is currently being invoked.",
    "cos202_046": "IOException is a checked exception, meaning the compiler forces the programmer to either catch it or declare it in the method signature using throws.",
    "cos202_047": "An interface provides a formal contract that classes must adhere to, facilitating polymorphism and enabling multiple inheritance of types.",
    "cos202_048": "In Java, instance variables are automatically initialized to default values; for boolean, that value is false.",
    "cos202_049": "The add() method is the standard way to append an element to the end of an ArrayList collection.",
    "cos202_050": "Method overloading allows you to define several methods with the same name, provided they have different parameter lists (different types or number of arguments), increasing code readability.",
    "cos202_051": "final prevents modification (variables/classes/methods), finally ensures code execution after a try-catch block, and finalize() is called by the Garbage Collector before an object is destroyed.",
    "cos202_052": "Without break, execution falls through to the next case. break ensures that once a matching case is executed, the control leaves the switch construct.",
    "cos202_053": "super() (with parentheses) explicitly calls the constructor of the immediate parent class, which is necessary for proper object initialization in an inheritance chain.",
    "cos202_054": "NullPointerException is an unchecked exception (a subclass of RuntimeException), meaning it does not need to be explicitly declared or caught.",
    "cos202_055": "The new keyword is used to allocate memory for a new object, followed by a call to the class constructor.",
    "cos202_056": "Encapsulation hides the internal data of an object and requires all interactions to happen through public methods, preventing accidental corruption of data.",
    "cos202_057": "Static blocks are initialized when the class is first loaded, making them ideal for setting up static variables or performing one-time initialization.",
    "cos202_058": "String is a class (a reference type) in Java, whereas int, boolean, and double are primitive types.",
    "cos202_059": "Unlike instance variables, Java local variables are not automatically initialized; the compiler will flag an error if you attempt to use them without explicit assignment.",
    "cos202_060": "The JVM interprets or compiles the bytecode into machine-specific instructions, which allows Java code to run on any device without modification ('Write Once, Run Anywhere').",
    "cos202_061": "A constructor is a special method that is called automatically when an object is instantiated; its primary role is to set the initial state of the object.",
    "cos202_062": "Interfaces in Java are declared using the interface keyword and implicitly contain public abstract methods; they do not contain method bodies (except for default/static methods in newer versions).",
    "cos202_063": "In integer division, the decimal part is truncated, so 10 / 3 results in the integer 3.",
    "cos202_064": "A Set is a collection that cannot contain duplicate elements, making it ideal for managing unique items.",
    "cos202_065": "A final class is locked; it prevents other classes from inheriting from it, which is often used for security or to ensure consistent behavior.",
    "cos202_066": "An event is an action that occurs, such as a mouse click, a key press, or a window resize, which the program must respond to.",
    "cos202_067": "The catch block provides the logic to recover or handle the error, preventing the program from crashing abruptly when an exception occurs.",
    "cos202_068": "The private modifier provides the highest level of encapsulation, restricting access to the class where the member is defined.",
    "cos202_069": "In Java, when you use the + operator with a String, it performs concatenation rather than addition. '5' + 5 results in the string '55'.",
    "cos202_070": "Recursion is a powerful programming technique where a function calls itself; it must include a base case to eventually stop the recursion.",
    "cos202_071": "A class defines the structure and behavior (the template), while an object is the actual entity created in memory based on that class definition.",
    "cos202_072": "In Java, the extends keyword is used when a class wants to inherit from another class (superclass).",
    "cos202_073": "Java evaluates expressions from left to right. It adds 10 + 20 (resulting in 30) first, then concatenates the resulting string '30' with 'Java'.",
    "cos202_074": "The Garbage Collector identifies objects that are no longer referenced by the program and reclaims their memory, preventing memory leaks.",
    "cos202_075": "Abstract classes are designed to be incomplete blueprints that provide common functionality while forcing subclasses to implement specific abstract methods.",
    "cos202_076": "In Java, checked exceptions like IOException must be handled either by surrounding the code with a try-catch block or by declaring it in the method signature using the throws keyword.",
    "cos202_077": "Event-driven programming is widely used in GUIs where the program waits for user interaction (events) to trigger specific blocks of code.",
    "cos202_078": "The == operator compares object references (memory addresses), while the equals() method compares the actual character sequence content of the strings.",
    "cos202_079": "A static variable is a class-level variable; all objects of that class share the same memory location for this variable.",
    "cos202_080": "The method signature consists of the method name and the number, order, and type of its parameters; it is what the compiler uses to distinguish between overloaded methods.",
    "cos202_081": "A List is an ordered collection that allows duplicates, whereas a Set is an unordered collection (usually) that enforces uniqueness, rejecting duplicate entries.",
    "cos202_082": "This is the shorthand syntax for initializing an array with specific values at the time of declaration.",
    "cos202_083": "If a subclass overrides a method but still needs to execute the logic defined in the parent class, it can use super.methodName() to call the parent version.",
    "cos202_084": "If an exception propagates up to the main thread without being caught, the default exception handler will print the stack trace and terminate the program.",
    "cos202_085": "FileNotFoundException is a checked exception because the compiler anticipates that files might not exist and requires the programmer to handle that possibility explicitly.",
    "cos202_086": "If no access modifier is specified, the member has package-private access, meaning it is visible to other classes within the same package.",
    "cos202_087": "The JVM executes bytecode, acting as an abstraction layer between the compiled Java code and the underlying hardware/OS, ensuring portability.",
    "cos202_088": "The public static void main(String[] args) method is the designated entry point that the JVM looks for to start running any Java application.",
    "cos202_089": "The && operator requires both conditions to be true. Since (3 > 5) is false, the entire expression evaluates to false.",
    "cos202_090": "The interface keyword is the standard and correct way to define an interface in Java.",
    "cos202_091": "The String[] args parameter allows the program to accept input provided by the user when executing the application from the command line.",
    "cos202_092": "The new operator is strictly required in Java to allocate memory on the heap for a new object instance.",
    "cos202_093": "Packages provide a namespace to group related classes together, which helps manage large projects and avoids conflicts when two classes have the same name.",
    "cos202_094": "The += operator is a compound assignment operator that adds the right operand to the variable on the left, so 5 + 3 equals 8.",
    "cos202_095": "While run() contains the code for the thread, calling start() is necessary to actually notify the JVM to spawn a new thread and execute the run() method concurrently.",
    "cos202_096": "Polymorphism allows a superclass variable to refer to any subclass object, enabling the code to be more flexible and extensible.",
    "cos202_097": "This is a ternary operator. The condition 10 > 5 is true, so it evaluates to the first expression ('Yes').",
    "cos202_098": "The super keyword provides a reference to the immediate parent object, allowing access to its methods and fields.",
    "cos202_099": "An abstract method must have the abstract keyword and end with a semicolon (no curly braces/body).",
    "cos202_100": "This runtime error occurs when the code tries to access an element at an index that is less than 0 or greater than or equal to the array's length.",
    "cos202_101": "Event listeners (like ActionListener) are interfaces that define methods to handle specific events, allowing the GUI to remain interactive.",
    "cos202_102": "java.awt (Abstract Window Toolkit) provides the basic components and event-handling mechanisms for creating GUI applications.",
    "cos202_103": "The event source is the UI component where the interaction occurs; it fires the event, which is then captured by a registered listener.",
    "cos202_104": "actionPerformed(ActionEvent e) is the standard method defined in the ActionListener interface that must be implemented to handle button clicks.",
    "cos202_105": "Iterative approaches rely on control structures like for or while loops, while recursive approaches solve the problem by repeatedly calling the same method with a smaller input.",
    "cos202_106": "Without a base case, there is no condition to stop the recursion, causing the system to run out of memory (stack space) as it repeatedly calls itself.",
    "cos202_107": "Binary search works by repeatedly dividing the search interval in half; it only works if the dataset is already sorted.",
    "cos202_108": "Bubble sort compares adjacent elements repeatedly; in the worst case, it requires approximately n² comparisons.",
    "cos202_109": "QuickSort uses a divide-and-conquer strategy by picking a pivot element and partitioning the array into sub-arrays before sorting them recursively.",
    "cos202_110": "Iterator is an interface in java.util that provides a safe way to iterate through collections like List or Set.",
    "cos202_111": "The delegation model relies on the Source (where the action happens), the Event (the data about the action), and the Listener (the code that responds to the action).",
    "cos202_112": "actionPerformed is the mandatory method defined by the ActionListener interface to receive and process action events.",
    "cos202_113": "When an event occurs on a component, the AWT framework propagates or sends an event object to all listeners that have been registered to handle that specific type of event.",
    "cos202_114": "Stacks are used for backtracking/undo operations, while Queues are used for buffer/scheduling tasks.",
    "cos202_115": "QuickSort effectively divides the array into two sub-arrays based on a pivot point and sorts them independently.",
    "cos202_116": "The Iterator interface abstracts away the underlying data structure (whether it's an Array or Linked List), allowing the same code to loop through any collection type.",
    "cos202_117": "OLE allows for integration between different software applications by allowing objects (like a chart from a spreadsheet) to be embedded in another document (like a word processor).",
    "cos202_118": "The do...while loop tests its condition AFTER executing the body, guaranteeing the body runs at least once. This is different from while and for loops which check the condition first.",
    "cos202_119": "When i==3, the continue statement skips that iteration, so 3 is never printed. All other values 1,2,4,5 are printed.",
    "cos202_120": "The for loop header format is: for(initialization; condition; increment). Example: for(int i=0; i<10; i++). The semicolons separate the three parts.",
    "cos202_121": "The continue statement skips remaining statements in the current loop iteration and jumps to the next iteration. It does NOT exit the loop entirely — that is what break does.",
    "cos202_122": "The while loop evaluates its condition BEFORE executing the body. If the condition is false initially, the body never executes (zero or more times).",
    "cos202_123": "The default case acts as a catch-all that executes when no other case label matches the switch expression. It is optional, not mandatory.",
    "cos202_124": "The loop increments x from 0: x becomes 1, 2, then 3. When x==3 the condition x<3 is false so the loop exits. println prints 3.",
    "cos202_125": "The enhanced for loop syntax is: for(type variable : arrayName). It iterates through each element automatically without needing an index counter.",
    "cos202_126": "According to the course material, Java programs are built from three control structures: sequence (default top-down), selection (if/switch), and repetition (while/for/do-while).",
    "cos202_127": "Java has exactly 8 primitive data types: byte, short, int, long, float, double, boolean, and char. All other types including String are reference/object types.",
    "cos202_128": "The char data type stores a single 16-bit Unicode character, allowing it to represent characters from virtually any language in the world.",
    "cos202_129": "int is a 32-bit signed two's complement integer. It can store values from -2,147,483,648 to 2,147,483,647.",
    "cos202_130": "long is a 64-bit signed integer used when int range is insufficient. It can hold much larger values than int.",
    "cos202_131": "All reference variables (objects, arrays) are automatically initialized to null if not explicitly set. null means the variable points to nothing.",
    "cos202_132": "String is a class in Java (java.lang.String), making it a reference type. int, boolean, and char are all primitive types predefined by the language.",
    "cos202_133": "Scanner is in the java.util package. You must write import java.util.Scanner; at the top of your program before using the Scanner class.",
    "cos202_134": "The nextInt() method reads the next integer token from the input stream. Other similar methods include nextDouble(), nextFloat(), and nextLine().",
    "cos202_135": "JOptionPane.showInputDialog() displays a pop-up dialog box prompting the user for input. It returns the input as a String.",
    "cos202_136": "JOptionPane is found in the javax.swing package. You need import javax.swing.JOptionPane; to use it.",
    "cos202_137": "BufferedReader's readLine() method reads a complete line of text as a String. It blocks until the user presses Enter.",
    "cos202_138": "BufferedReader operations can throw an IOException (a checked exception) if the input stream fails, so the compiler forces you to handle it with try-catch.",
    "cos202_139": "System.out is the standard output stream object. System.out.print() and System.out.println() both write to it. System.err is for error output.",
    "cos202_140": "The correct syntax for a 2D array is: int[][] arr = new int[rows][columns]; The double bracket notation [][] indicates a 2D array.",
    "cos202_141": "Array indices are zero-based. Second row = index 1, third column = index 2. So arr[1][2] accesses row 2 col 3.",
    "cos202_142": "A 2D array initializer uses nested curly braces where each inner set represents one row: { {row0values}, {row1values} }.",
    "cos202_143": "For a 2D array, array.length gives the number of rows. To get the number of columns in row i, use array[i].length.",
    "cos202_144": "The package keyword declares which package a class belongs to. It must be the first statement in a Java source file: package mypack;",
    "cos202_145": "import package.*; imports all public classes and interfaces from that package. import package.ClassName; imports only the specified class.",
    "cos202_146": "A subpackage is a package nested inside another package, used to further categorize related classes. Example: java.util is a subpackage of java.",
    "cos202_147": "Packages help organize code, protect access, and prevent naming conflicts, but they do NOT affect execution speed. Speed is determined by the code logic and JVM.",
    "cos202_148": "The % operator returns the remainder of division. 10 divided by 3 is 3 remainder 1, so 10 % 3 = 1.",
    "cos202_149": "Local variables in Java have no default value and must be explicitly initialized before use. Using 'total' without assigning it a value causes a compile-time error.",
    "cos202_150": "String literals in Java are stored in a string pool, so 'a' and 'b' both point to the same object — making == return true. equals() also returns true as both contain 'Hello'.",
    "cos202_151": "Java arrays are zero-indexed. arr has indices 0,1,2 only. Accessing index 5 throws ArrayIndexOutOfBoundsException at runtime.",
    "cos202_152": "When i=0, it prints '0 '. When i=1, break exits the loop immediately. So only '0' is printed.",
    "cos202_153": "This demonstrates runtime polymorphism. Even though 'a' is declared as Animal, it holds a Dog object. Java calls Dog's sound() method — this is method overriding.",
    "cos202_154": "The do...while loop always executes its body at least once. So '1 ' is printed, then i becomes 2, and the condition i<1 is false, so the loop ends.",
    "cos202_155": "If a class extends an abstract class, it must provide implementations for ALL abstract methods, or the subclass itself must be declared abstract.",
    "cos202_156": "x++ is post-increment: it uses the current value (5) first, then increments. So println(x++) prints 5, then x becomes 6, and the next println prints 6.",
    "cos202_157": "Division by zero throws ArithmeticException, so 'OK' is skipped and 'Error' is printed by the catch block. The finally block ALWAYS executes, so 'Done' prints too."
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = COS202_EXPLANATIONS;
}
