// CSC203 - Discrete Structures Explanations

const CSC203_EXPLANATIONS = {
    0: "A proposition is a statement that is either true or false. Option C is a declarative statement with a truth value.",
    1: "By De Morgan's Law: ¬(p ∧ q) = ¬p ∨ ¬q.",
    2: "A conditional statement is false only when True → False.",
    3: "Contrapositive swaps and negates both: p → q becomes ¬q → ¬p.",
    4: "Number of subsets = 2ⁿ. So 2⁴ = 16.",
    5: "Intersection means common elements.",
    6: "Reflexive means every element relates to itself.",
    7: "One-to-one (injective) means no two inputs share the same output.",
    8: "5! = 5×4×3×2×1 = 120.",
    9: "⁵C₂ = 5!/2!3! = 10.",
    10: "Maximum edges = n(n−1)/2 = 4×3/2 = 6.",
    11: "Complete graph connects every pair of vertices.",
    12: "Induction proves statements for natural numbers/integers.",
    13: "It verifies the statement is true for the first value.",
    14: "⁵P₃ = 5×4×3 = 60.",
    15: "These three properties define equivalence relation.",
    16: "A connected graph with all even degrees has Euler circuit.",
    17: "Depends only on previous term → first order linear.",
    18: "Complement of universal set is empty set.",
    19: "|A × B| = |A| × |B| = 3×4 = 12.",
    20: "If p is false, only q remains true → expression becomes q ∧ ¬p.",
    21: "Total subsets = 2³ = 8. Proper subsets exclude the set itself → 8 − 1 = 7.",
    22: "Mutual inclusion implies equality.",
    23: "It is reflexive, antisymmetric, and transitive → partial order.",
    24: "Onto (surjective) means every element in codomain is mapped to.",
    25: "Biconditional is true when both are same (TT or FF).",
    26: "4! = 24 permutations.",
    27: "A tree has n − 1 edges → 7 − 1 = 6.",
    28: "Symmetry means reverse pair exists.",
    29: "nC₀ = 1 for any n.",
    30: "A tree is acyclic connected graph.",
    31: "Even empty set has one subset — itself.",
    32: "Degree counts incident edges.",
    33: "⁴P₃ = 4×3×2 = 24.",
    34: "Depends on aₙ₋₁ and aₙ₋₂ → second order.",
    35: "p ∨ ¬p is always true.",
    36: "No edges within same set.",
    37: "2⁵ = 32.",
    38: "A ∪ ∅ = A.",
    39: "Exactly two odd-degree vertices → Euler path.",
    40: "Intersection means common elements. Both sets share 2 and 4.",
    41: "Complement contains elements in U not in A.",
    42: "By De Morgan's Law.",
    43: "Implication only false when T → F.",
    44: "2⁴ = 16.",
    45: "Identity relation satisfies all three properties.",
    46: "5 × 4 × 3 × 2 × 1 = 120.",
    47: "⁵C₃ = 10.",
    48: "Definition of a tree.",
    49: "Degree counts incident edges.",
    50: "Standard formula for sum of first n natural numbers.",
    51: "Standard binomial expansion.",
    52: "Injective function definition.",
    53: "n(n−1)/2 → 4×3/2 = 6.",
    54: "Euler path condition.",
    55: "A set is a well-defined collection of distinct elements.",
    56: "Subset means all elements of A are contained in B.",
    57: "Power set contains all subsets including empty set and the set itself.",
    58: "A − B means elements in A not in B → 1 and 2.",
    59: "Negation of OR becomes AND of negations.",
    60: "Reflexive means every element is related to itself.",
    61: "Each input must have exactly one output.",
    62: "Injective means no two inputs share the same output.",
    63: "5! = 120.",
    64: "⁷C₃ = 35.",
    65: "Graph = vertices + edges.",
    66: "Euler circuit condition.",
    67: "Induction proves statements for all n ∈ ℕ.",
    68: "Standard binomial expansion.",
    69: "Fundamental tree property.",
    70: "a₁ = 2 × 1 = 2."
};

// Export for use in exam system
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CSC203_EXPLANATIONS;
}
