// SEN201 - Software Engineering Explanations

const SEN201_EXPLANATIONS = {
    0: "Software engineering focuses on structured methods to build and maintain software.",
    1: "Software includes programs plus related documentation and data.",
    2: "Maintainability measures how easily software can be updated.",
    3: "Software does not physically degrade like hardware.",
    4: "Quality + cost + schedule control is the core goal.",
    5: "A process defines development steps.",
    6: "Requirements engineering is a core process activity.",
    7: "Waterfall follows linear sequential stages.",
    8: "Changes are difficult once development begins.",
    9: "System is built and delivered in increments.",
    10: "Reuse reduces cost and development time.",
    11: "It identifies system needs and constraints.",
    12: "Functional requirements define system behavior.",
    13: "They describe system qualities and constraints.",
    14: "They are understandable by non-technical users.",
    15: "They guide implementation.",
    16: "Validation checks correctness of requirements.",
    17: "Requirements evolve during development.",
    18: "Models help analyze system design.",
    19: "UML is a standard modeling language.",
    20: "They show system environment relationships.",
    21: "They show interactions and workflows.",
    22: "They represent system structure.",
    23: "They show system changes over time.",
    24: "Architecture defines system structure.",
    25: "Patterns solve recurring design issues.",
    26: "Clients request, servers respond.",
    27: "Layers isolate changes.",
    28: "Design defines implementation structure.",
    29: "OOP organizes software around objects.",
    30: "It structures data storage.",
    31: "It improves user experience.",
    32: "Debugging removes detected defects.",
    33: "Testing identifies faults.",
    34: "Verification = build product right.",
    35: "Validation = build right product.",
    36: "Tests smallest units of code.",
    37: "Tests module interaction.",
    38: "Full system evaluation.",
    39: "Users confirm system meets needs.",
    40: "Tests guide development.",
    41: "Software continues to change after release.",
    42: "Maintenance includes updates and improvements.",
    43: "It fixes bugs.",
    44: "It adapts software to change.",
    45: "Dependability means trustworthiness.",
    46: "Reliability = failure-free operation probability.",
    47: "Security protects system assets.",
    48: "Risk = possible future problem.",
    49: "Management controls project execution.",
    50: "Planning predicts effort, cost, and resources.",
    51: "A schedule defines activity timing.",
    52: "Risk refers to possible future issues.",
    53: "It identifies possible threats.",
    54: "It evaluates risk severity and probability.",
    55: "Planning prepares responses to risks.",
    56: "Monitoring tracks risk status.",
    57: "Software is developed collaboratively.",
    58: "Requirements often evolve.",
    59: "Changing needs require updates.",
    60: "Perfective maintenance enhances system performance.",
    61: "Preventive maintenance prevents future faults.",
    62: "Improves internal structure only.",
    63: "Dependability means trustworthiness.",
    64: "Safety protects people and environment.",
    65: "Vulnerability is a security weakness.",
    66: "Components communicate over networks.",
    67: "Client initiates service request.",
    68: "Server responds to requests.",
    69: "Layers separate responsibilities.",
    70: "Each node can provide and request services.",
    71: "SOA uses loosely coupled services.",
    72: "Web services enable system communication.",
    73: "RPC enables remote execution.",
    74: "Communication is via messages.",
    75: "Validation confirms correct system.",
    76: "Testing finds errors, debugging fixes them.",
    77: "Test case defines expected behavior.",
    78: "Tests external behavior.",
    79: "Tests internal implementation.",
    80: "Ensures modifications don't break system.",
    81: "Documentation supports understanding.",
    82: "It explains system usage.",
    83: "It supports development and maintenance.",
    84: "It manages system changes.",
    85: "They manage code versions.",
    86: "Baseline is an approved reference version.",
    87: "SQA ensures quality processes.",
    88: "They find issues before execution.",
    89: "It evaluates project viability.",
    90: "It evaluates financial value.",
    91: "It checks technical capability.",
    92: "It evaluates usability and acceptance.",
    93: "Reuse saves development time.",
    94: "Prototype helps understanding requirements.",
    95: "It is not part of final system.",
    96: "Prototype evolves into final product.",
    97: "It improves requirement understanding.",
    98: "Quality and usefulness are primary goals.",
    99: "Management controls schedule and cost.",
    100: "Process improvement enhances quality and productivity.",
    101: "Legacy systems remain operational despite age.",
    102: "Productivity compares results to effort.",
    103: "Standards enforce best practices.",
    104: "Agile values flexibility and collaboration.",
    105: "Spiral model integrates iteration and risk management.",
    106: "Iteration refines the system gradually.",
    107: "CI integrates and tests code regularly.",
    108: "Traceability tracks requirement relationships.",
    109: "Ambiguity leads to incorrect implementation.",
    110: "It determines project viability.",
    111: "Stakeholders include all affected parties.",
    112: "Cohesion measures internal relatedness.",
    113: "Low coupling improves flexibility.",
    114: "Architecture strongly influences the system.",
    115: "Patterns solve common design challenges.",
    116: "Static testing inspects artifacts.",
    117: "Dynamic testing runs the program.",
    118: "A defect is an error or flaw.",
    119: "QC ensures product quality.",
    120: "Technology evolution makes systems outdated.",
    121: "It extracts design information.",
    122: "Portable software runs on multiple platforms.",
    123: "Estimation predicts project effort.",
    124: "Milestones mark progress checkpoints.",
    125: "Items under configuration control are tracked.",
    126: "It manages modifications responsibly.",
    127: "Quality involves multiple characteristics.",
    128: "Fixing defects improves reliability.",
    129: "Validation confirms user needs are met.",
    130: "Verification checks correctness.",
    131: "Lifecycle models structure development.",
    132: "Components can be reused.",
    133: "Interfaces define interactions.",
    134: "Coupling measures module dependency.",
    135: "Cohesion measures internal unity.",
    136: "Deployment releases software.",
    137: "They determine success conditions.",
    138: "Environment supports testing activities.",
    139: "Metrics quantify software properties.",
    140: "Clear documentation aids maintenance.",
    141: "Mitigation reduces risk severity.",
    142: "Reviews assess quality.",
    143: "Good requirements must be precise.",
    144: "Scalability supports growth.",
    145: "Integration builds full system.",
    146: "Maintenance consumes most resources.",
    147: "Usability measures user experience.",
    148: "QA prevents defects.",
    149: "Success depends on people, process, and tools."
};

// Export for use in exam system
if (typeof module !== 'undefined' && module.exports) {
    module.exports = SEN201_EXPLANATIONS;
}
